In [1]:
import json
import pickle
import numpy as np
import codecs

In [2]:
# with codecs.open('ingredients.json', 'r', encoding='ascii') as fr:
#     ingr_list = json.load(fr)
    
# with codecs.open('clean_data_revised_names.json', 'r', encoding='ascii') as fr:
#     drink_list = json.load(fr)

with open('ingredients.json', 'r') as fr:
    ingr_list = json.load(fr)
    
with open('clean_data_revised_names.json', 'r') as fr:
    drink_list = json.load(fr)
    
#with f = codecs.open('file.txt', encoding='utf-8'):
    
#pickle.dump(ingr_list, open( "ingr_lst_pickle_jsondump.p", "wb" ), protocol=2 )
#pickle.dump(drink_ingr, open( "drink_ingr_pickle_jsondump.p", "wb" ), protocol=2 )
#pickle.dump(drink_list, open( "drink_dic_pickle_jsondump.p", "wb" ), protocol=2 )

    
ingr_list = [x.lower().encode('ascii', 'ignore') for x in ingr_list]
#ingr_list = pickle.load( open("ingr_lst_pickle.p", "rb" ))
#drink_ingr = pickle.load( open( "drink_ingr_pickle.p", "rb" ))
#drink_list = pickle.load( open( "drink_dic_pickle.p", "rb" ))
#ingr_list = [x.lower().encode('ascii', 'ignore') for x in ingr_list]
#print(ingr_list)
#def create_ingr_array

#ingr_nplst = np.array(ingr_list)
#print(ingr_nplst)

#print(drink_list)

In [3]:
#index = np.where(ingr_nplst=='Tang')
#print(index)
#print(drink_list)
# drink_list_new = {}
# for k,v in drink_list.items():
#     drink_name = k.lower().encode('ascii', 'ignore')
#     recipe = []
#     for tup in v:
#         ing_name = tup[0].lower().encode('ascii', 'ignore')
#         ing_amt = tup[1].lower().encode('ascii', 'ignore')
#         recipe.append([ing_name, ing_amt])
#     drink_list_new[drink_name] = recipe
# drink_list = drink_list_new

In [4]:
print(ingr_list)
print(type(ingr_list[0]))

['151 proof rum', '190 proof everclear', '7-up', 'absinthe', 'absolut peppar', 'acerola', 'advocaat', 'aftershock', 'ale', 'aliz', 'allspice', 'almond', 'almond flavoring', 'almond syrup', 'amaretto', 'amarula cream', 'amer picon', 'angelica root', 'angostura bitters', 'anise', 'anisette', 'aperol', 'apfelkorn', 'apple', 'apple brandy', 'apple cider', 'apple juice', 'apple schnapps', 'apple-cranberry juice', 'apricot', 'apricot brandy', 'apricot liqueur', 'apricot nectar', 'aquavit', 'asafoetida', 'avocado', 'aejo rum', "bailey's irish cream", 'banana', 'banana liqueur', 'banana rum', 'banana syrup', 'batida de coco', 'battery', 'beef bouillon', 'beer', 'berries', 'bitter lemon', 'bitters', 'black sambuca', 'black pepper', 'black rum', 'black vodka', 'blackberries', 'blackberry brandy', 'blackberry schnapps', 'blackcurrant cordial', 'blackcurrant schnapps', 'blackcurrant squash', 'blackcurrant vodka', 'blended whiskey', 'bloody mary mix', 'blue curacao', 'blueberries', 'blueberry schna

In [5]:
ingr_to_num = {}
i=0
for ingr in ingr_list:
    ingr_to_num[ingr] = i
    i=i+1

In [6]:
print(ingr_to_num)
for k,v in ingr_to_num.items():
    print(type(k))

{'cherry cola': 92, 'ale': 8, 'grape juice': 200, 'blackcurrant schnapps': 57, 'absolut peppar': 4, 'wild turkey': 488, 'milk': 302, 'blueberries': 63, 'pineapple juice': 357, "rose's sweetened lime juice": 394, 'triple sec': 458, 'cayenne pepper': 85, 'vanilla extract': 463, 'canadian whisky': 74, 'ginger ale': 190, 'lemon liqueur': 256, 'soy milk': 422, 'ouzo': 326, 'chocolate liqueur': 101, 'fruit punch': 181, 'light rum': 267, 'hot damn': 225, '151 proof rum': 0, 'tennessee whiskey': 451, 'grain alcohol': 197, 'vanilla syrup': 467, 'hot red pepper flakes': 227, 'cinzano bitters': 108, 'oreo cookie': 324, 'apple cider': 25, 'grape schnapps': 201, 'swedish punsch': 441, 'tea': 450, 'almond': 11, 'sloe gin': 415, 'port': 371, 'cynar': 154, 'guava syrup': 214, 'white wine': 486, 'collins mix': 129, 'tequila rose': 453, 'raspberry vodka': 384, 'cocoa powder': 116, 'tabasco sauce': 446, 'water': 472, 'raspberries': 377, 'apfelkorn': 22, 'blackberry schnapps': 55, 'johnnie walker': 240, '

In [7]:
drink_to_num = {}
num_to_drink = {}
j=0
for k,v in drink_list.items():
    drink_to_num[k] = j
    num_to_drink[j] = k
    j=j+1
#print(num_to_drink)

In [9]:
#let's make the drink by ingredients numpy array, so we can eventually pickle it
drink_ingr = np.zeros((len(drink_to_num), len(ingr_to_num)))
for i in range(len(drink_to_num)):
    curr_ingredients = drink_list[num_to_drink[i]]
    #for j in range(len(ingr_to_num)):
    for ingredient in curr_ingredients:
        #print(ingredient[0])
        #print(type(ingredient[0]))
        #print(type(ingredient[0].encode('ascii', 'ignore')))
        num_ingredient = ingr_to_num[ingredient[0].lower().encode('ascii', 'ignore')]
        drink_ingr[i][num_ingredient] = 1
print(drink_ingr)
print(np.sum(drink_ingr, axis=1))
drink_ingr = pickle.load( open( "drink_ingr_pickle.p", "rb" ))
print(np.sum(drink_ingr, axis=1))
# for thing in drink_ingr:
#     for thing2 in thing:
#         print(thing2)

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
[3. 5. 3. ... 5. 4. 2.]
[3. 2. 5. ... 4. 2. 2.]


In [13]:
def drink_to_index(dr):
    return drink_to_num[dr]
def index_to_drink(num):
    return num_to_drink[num]
    
def ingredient_to_index(ingredient_str):
    return ingr_to_num[ingredient_str.lower()]
def number_list_of_drinks(ing_str_lst):
    newlst = []
    for ingr in ing_str_lst:
        newlst.append(ingredient_to_index(ingr))     
    return newlst

def get_ingredients_for_drink(drink_num, drink_lst):
    #print(drink_num)
    curr_ingredients = drink_lst[index_to_drink(drink_num)]
    final = []
    for ing in curr_ingredients:
        final.append(ingredient_to_index(ing[0]))
    return final

#returns a numpy array of 1 by size of drink_list. each entry is the jaccard similarity between the user input and drink
def drink_jaccard_sim(user_ingredients_lst, drink_lst):
    final_mat = np.zeros(len(drink_lst))
    #cat1 will be the user set. It should just have a list of numbers that correspond to drinks
    cat1 = set(number_list_of_drinks(user_ingredients_lst))
    print(cat1)
    for i in range(len(drink_lst)):
        #cat2 will be the ingredients of each individual drink
        cat2 = set(get_ingredients_for_drink(i, drink_lst))
        print(cat2)
        #do the jaccard
        intersect = len(set.intersection(cat1, cat2))
        union = len(set.union(cat1, cat2))
        final_mat[i] = intersect/(union+1)
    return final_mat
    

In [14]:
sample_ingredient_list = ["Banana liqueur",
"Banana rum",
"Banana syrup",
"Batida de Coco",
"Battery",
"Beef bouillon",
"Beer",
"Berries",
"Bitter lemon",
"Bitters",
"Black Sambuca",
"Black pepper",
"Black rum",
"Black vodka",
"Blackberries",
"Blackberry brandy",
"Blackberry schnapps",
"Blackcurrant cordial",
"Blackcurrant schnapps",
"Blackcurrant squash",
"Blackcurrant vodka",
"Blended whiskey",
"Bloody mary mix",
"Blue Curacao",
"Blueberries",
"Blueberry schnapps"]

sample_ingredient_list2 = ['vodka', 'sugar', 'orange']
sample_ingredient_list3 = ["Cherry", "Coconut", "Cognac", "Cranberry vodka", "Ice", "Lemon", "Strawberries"]

sim_lst = drink_jaccard_sim(sample_ingredient_list2, drink_list)
print(sim_lst)
for thing in sim_lst:
    print(thing)

set([312, 437, 471])
set([257, 93, 471])
set([472, 409, 257, 437, 255])
set([452, 253, 446])
set([409, 18, 443, 289])
set([33, 428])
set([195, 183, 14, 143])
set([316, 20, 471])
set([229, 444, 109, 301])
set([196, 301])
set([48, 188])
set([164, 212, 443, 188, 357])
set([66, 188, 325, 255])
set([244, 349, 302, 471])
set([88, 2, 475, 260])
set([65, 420, 229, 270])
set([14, 244, 37, 198, 471])
set([91, 443, 188])
set([136, 469, 62, 471])
set([320, 409, 231])
set([169, 178, 181])
set([212, 316, 471])
set([136, 14])
set([100, 229, 139, 464, 244, 471, 37])
set([420, 198, 455, 136, 396, 45, 244, 471, 188])
set([130, 163, 125, 477])
set([444, 458, 236, 421, 316])
set([280, 260, 316, 212, 55])
set([123, 244, 437, 302, 229])
set([420, 357, 425, 121, 316, 62, 229])
set([2, 38, 333, 430, 207, 471, 377, 90])
set([144, 255, 212, 471])
set([316, 283, 188, 212, 229])
set([160, 204, 91, 291, 188])
set([401, 458, 188])
set([336, 232, 22])
set([196, 260, 158])
set([356, 421, 339, 212, 280, 316])
set([387

KeyError: u'j\xe4germeister'

In [20]:
def get_top_k_drinks(lst, k):
    #lst should have a list of ranked values, just need to do an argsort for the best ones
    sorted_lst = lst.argsort()[-k:][::-1]
    print(sorted_lst)
    top_drinks = []
    for drink_num in sorted_lst:
        #top_drinks.append(index_to_drink(drink))
        top_drinks.append((index_to_drink(drink_num), lst[drink_num]))
    return top_drinks

thing = get_top_k_drinks(sim_lst, 10)
print(thing)

[6072 2027 2018 2019 2020 2021 2022 2023 2024 2025]
[(u'Sour Cow', 0.0), (u'Lava Lamp #2', 0.0), (u'Evil Princess', 0.0), (u'Spiced Cherry', 0.0), (u'Golden Eye', 0.0), (u'Extra Fuzzy Navel', 0.0), (u'Flaming Rasta', 0.0), (u'Hell Mary', 0.0), (u'San Patricio', 0.0), (u'Opening Cocktail', 0.0)]


In [27]:
#pickle.dump(ingr_list, open( "ingr_lst_pickle.p", "wb" ), protocol=2 )
#pickle.dump(drink_ingr, open( "drink_ingr_pickle.p", "wb" ), protocol=2 )
#pickle.dump(drink_list, open( "drink_dic_pickle.p", "wb" ), protocol=2 )

In [28]:
ingr_lst1 = pickle.load( open( "ingr_lst_pickle.p", "rb" ))

In [29]:
#print(ingr_lst1)

In [30]:
#print(ingr_to_num)
#print(ingr_to_num["u'Cherry Heering'"])

In [31]:
ingr_list = pickle.load( open("ingr_lst_pickle.p", "rb" ))
drink_ingr = pickle.load( open( "drink_ingr_pickle.p", "rb" ))
drink_list = pickle.load( open( "drink_dic_pickle.p", "rb" ))
ingr_list = [x.lower().encode('ascii', 'ignore') for x in ingr_list]

In [32]:
sim_lst = drink_jaccard_sim(sample_ingredient_list2, drink_list)
thing2 = get_top_k_drinks(sim_lst, 10)
print(thing2)

[2828 4253 5946 3822 4712 1559 5577 3974 3464 4781]
[('Caribbean Orange Liqueur', 0.75), ('Saurian Brandy', 0.6), ('Stockholm "75"', 0.5), ('Raspberry Cordial', 0.4), ('Lemon Shooters', 0.4), ('St. Petersburg', 0.4), ('Body Shot', 0.4), ('Piggelin #1', 0.4), ('The Power of Milk', 0.4), ('Top Banana', 0.4)]


In [18]:
#print(drink_list)

In [19]:
with open('alcoholic_cocktails_webtender_mixing.json', 'r') as fr:
    mixing_instructions = json.load(fr)

In [20]:
#print(mixing_instructions)

In [21]:
pickle.dump(mixing_instructions, open( "mixing_instructions.p", "wb" ), protocol=2 )